#!/bin/bash
set -eux
source $(dirname $0)/../common

install-packages keychain

install -m 0700 -o $user -g $user -d $home/.ssh
install -m 0600 -o $user -g $user $(dirname $0)/authorized_keys $home/.ssh/authorized_keys
