#!/bin/bash
set -eu
source $(dirname $0)/../common

which git || install-packages git

install -m 0700 -o $user -g $user -d $home/git

install -m 0400 -o $user -g $user $(dirname $0)/gitconfig $home/.gitconfig
install -m 0400 -o $user -g $user $(dirname $0)/gitignore $home/.gitignore
