#!/bin/bash
set -eux
source $(dirname $0)/lib/functions
ts=$(dirname $0)/tools

ensure-root

for t in \
  user \
  bash \
  ssh \
  git \
  vim \
  irssi \
  timezone \
  tmux ; do
    $ts/$t/setup
done
