#!/bin/bash
set -eu
source $(dirname $0)/../common

which vim || install-packages vim

rm -rf $home/.vim
cp -r $(dirname $0)/vim $home/.vim
chown -R $user:$user $home/.vim

install -m 0400 -o $user -g $user $(dirname $0)/vimrc $home/.vimrc

ok "setup vim."
