#!/bin/bash
set -eu
source $(dirname $0)/../../lib/functions

install-packages golang golang-go.tools

install -m 0755 -o $user -g $user -d $home/go/src
install -m 0500 -o $user -g $user $(dirname $0)/go $home/.bashrc.d/go

