#!/bash/bash
set -eu
source $(dirname $(readlink -f $BASH_SOURCE))/defaults

red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'

ok() {
  echo -e "${green}$*${nc}"
}

die() {
  echo -e "${red}$*${nc}"
  exit 1
}

install-packages() {
  DEBIAN_FRONTEND=noninteractive apt-get install --yes $*
}

ensure-root() {
  if [ $(id -ur) != 0 ]; then
    die "this script must be run as root"
  fi
}

add-user() {
  local user=$1
  id $user || useradd $user --system -m -s /bin/false
}

write-as-user() {
  cat > $1
  chown $user:$user $1
}

is-osx() {
  uname | grep -i darwin
}

is-ubuntu() {
  [ -e /etc/os-release ] && grep -i pretty_name /etc/os-release | grep -i ubuntu >/dev/null
}

is-debian() {
  [ -e /etc/os-release ] && grep -i pretty_name /etc/os-release | grep -i debian >/dev/null
}
