#!/bin/bash
set -eu
source $(dirname $0)/../../lib/functions

install-packages git

install -m 0700 -o $user -g $user -d $home/git

install -m 0700 -o $user -g $user $(dirname $0)/gitconfig $home/.gitconfig
install -m 0700 -o $user -g $user $(dirname $0)/gitignore $home/.gitignore

sudo -u $user echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $home/.ssh/config
