#!/bin/bash
set -eux
source $(dirname $0)/../common

id $user || sudo useradd -m $user -s /bin/bash

echo "$user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$user
chmod 0440 /etc/sudoers.d/$user
visudo -c
