call pathogen#infect()

syntax on

" croshairs
set cursorline
"highlight  CursorLine ctermbg=234 ctermfg=white
set cursorcolumn
"highlight  CursorColumn ctermbg=234 ctermfg=white

" 256-color mode
set t_Co=256

colorscheme busybee

set tabstop=4
set shiftwidth=4
set expandtab

let mapleader=","
noremap<Leader>t :!rake spec<enter>



highlight ExtraWhitespace ctermbg=darkred guibg=#382424
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
" the above flashes annoyingly while typing, be calmer in insert mode
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/

function! s:FixWhitespace(line1,line2)
    let l:save_cursor = getpos(".")
    silent! execute ':' . a:line1 . ',' . a:line2 . 's/\s\+$//'
    call setpos('.', l:save_cursor)
endfunction

" Run :FixWhitespace to remove end of line white space.
command! -range=% FixWhitespace call <SID>FixWhitespace(<line1>,<line2>)



